### ISSUE TITLE
After creating LocalizeSettings, the NRE error occurs

### ISSUE THREAD

**Issue by Red-Cat-Fat** [elmortem/localization#1]
After creating LocalizeSettings, the NRE error occurs:
> NullReferenceException: Object reference not set to an instance of an object
Localization.Editor.LocalizeSettingsEditor.OnInspectorGUI () (at Packages/localization/Editor/Scripts/LocalizeSettingsEditor.cs:36)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <7af1774c9e44458e98ffdab661770f41>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by Red-Cat-Fat** [comment]
This happens for the first time in an empty project. I assume this is because you are trying to iterate over an array that has not been initialized:
```
LocalizeSettings.cs:30:
 public LocaleItem[] Locales;
```

**Comment by elmortem** [comment]
Fixed at 1.0.4
