### ISSUE TITLE
ReSharper disable once CheckNamespace

### ISSUE THREAD

**Issue by Red-Cat-Fat** [elmortem/localization#4]
![image](https://github.com/elmortem/localization/assets/28541280/44e22ea4-06f1-45ad-ad8c-1cf0c145d514)
The default IDE settings swear at an incorrect Namespace. To remove the need to add exception comments like:
```
// ReSharper disable once CheckNamespace
```
I suggest adding Localization to RootNamespace inside the package.
![image](https://github.com/elmortem/localization/assets/28541280/45e6f3ed-565a-4171-b97a-92a94bb5b4de)

**Comment by elmortem** [comment]
Fixed at 1.0.5
